name: ReformCloudAPISpigot
version: 2.0
author: ReformCloud
main: systems.reformcloud.launcher.SpigotBootstrap
api-version: 1.13

load: STARTUP

commands:
  reformsigns:
    aliases:
      - rs
      - signs
      - cloudsigns
